baseURL = 'https://tose.dev/'

theme = "hugo-bearneo"

title = 'tose.dev'

languageCode = 'en-us'

defaultContentLanguage = "en-gb"

[permalinks]
  posts = "/n/:slug"

[params]
    title = "Tose dev"
    description = "A Hugo theme. ✨ Transplanted from Hugo Bear Blog. Based on ʕ•ᴥ•ʔ Bear Blog."
    [params.RSS]
        enableRSS = false
    [params.footer]
        hideSitemap = true
    [params.author]
        name = "Gabriele Toselli"
        email = "toselli.gabriele@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
