baseURL = 'https://tose.dev/'

theme = "hugo-bearneo"

title = 'Tose.dev'

languageCode = 'en-us'

defaultContentLanguage = "en-gb"

enableGitInfo = true


[permalinks]
  posts = "/n/:slug"

[params]
    [params.RSS]
        enableRSS = false
    [params.footer]
        hideSitemap = true
    [params.author]
        name = "Gabriele Toselli"
        email = "toselli.gabriele@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
