title = 'tose.dev'
baseURL = 'https://tose.dev/'

# This is what goes in <html lang="">
languageCode = 'en-us'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.



[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"


[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/toselli-gabriele/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/gtoselli"


[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="notes"
    name = 'Notes'
    url = '/notes/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params]
  sitename = "Tose"
  defaultColor = "dark"
  description = "description"
  mainSections = ['notes']
  toc = false
  tocOpen = false
  goToTop = true

[Languages.en-gb.params.author]
  avatar = "avatar.jpg"
  intro = "Tose.dev"
  name = "Gabriele Toselli"
  description = "short bio"
